language: csharp
dist: xenial
mono: none
dotnet: 2.2
install:
- dotnet restore
script:
- dotnet build
- dotnet test test/Tests.Unit/Tests.Unit.csproj
- dotnet test test/Tests.Integration/Tests.Integration.csproj
